added the summary into the apihandlers sections and refactored to support go-commons changes

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -4,15 +4,39 @@ jobs:
   build:
     name: Build
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      # perform matrix testing to give us an earlier insight into issues with different versions of supported major versions of Go
+      matrix:
+        version:
+        - "1.22"
+        - "1.23"
+        - "1.24"
     steps:
       - name: Check out source code
-        uses: actions/checkout@v3
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
 
       - name: Set up Go
-        uses: actions/setup-go@v3
+        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
         with:
-          go-version-file: 'go.mod'
+          go-version: ${{ matrix.version }}
 
       - name: Run `make generate`
         run: make generate
+        env:
+          # A combination of our GitHub Actions setup, with the Go toolchain, leads to inconsistencies in calling `go env`, in particular with Go 1.21, where having (the default) `GOTOOLCHAIN=auto` results in build failures
+          GOTOOLCHAIN: local
 
+  results:
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+    name: Check generation results
+    needs: [build]
+    steps:
+      - run: |
+          result="${{ needs.build.result }}"
+          if [[ $result == "success" || $result == "skipped" ]]; then
+            exit 0
+          else
+            exit 1
+          fi
